version: '3.1'

services:

  userbot:
    container_name: user
    build: .
    volumes:
      - .:/src
    command: python app.py
    restart: always
    network_mode: "host"

    env_file:
      - ".env"

